# Generated by Django 3.1.3 on 2020-11-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201125_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertise',
            name='suspend',
            field=models.DateTimeField(),
        ),
    ]
